### ISSUE TITLE
settings.pyのDEBUGの問題

### ISSUE THREAD

**Issue by sacky3105** [sacky3105/django_app#15]
### As Is(今の状態)

- settings.pyのDEBUGの設定をFalseにするとUIの画面が真っ白になる。
- Falseの設定にしなければ本番環境ではアンチパターン

### To Be(理想の状態)

- Falseにしてもデザインパターンが崩れないようにする。

### 課題

①キャッシュをクリアする。
②動作確認用の環境と本番環境のブランチを切り分けし、本番環境のブランチでは
　DEBUGの影響がデザインに及ばないようにする。

**Comment by naritomo08** [comment]
mysqlコンテナを私が持ってる設定に作り替えたら私の環境でコンテナ動きました。
mac限定なので、プルリクはしません。
問題は再現しました。
Falseに設定変更した後キャッシュクリアしたら背景消えます。 (初回アクセスでも再現)
逆にTrueへの変更ではすぐに画面が更新されます。

**Comment by sacky3105** [comment]
承知しました。コメントありがとうございます。

**Comment by naritomo08** [comment]
以下の手順で解決しました。
私のローカルではDebug Falseでも動いています。

・コンテナにログインして、staticフォルダを作成する。
docker-compose exec web /bin/bash
python manage.py collectstatic

・settings.py,urls.pyを以下の内容に書き換える。

settings.py

DEBUG = False

urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('folders/', include('todo.urls')),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

**Comment by naritomo08** [comment]
対応としては以下の方法を提案します。

・Dockerfileへ以下のコマンドを追記

RUN python manage.py collectstatic

・settings.py,urls.pyを以下の内容に書き換える。

settings.py

以下の行をこの記載にする。
DEBUG = False

urls.py

最後の部分をいかないようにする。
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
path('admin/', admin.site.urls),
path('folders/', include('todo.urls')),
re_path(r'^static/(?P.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

・コミットする。

・本番サーバに入り、以下のコマンドを入力し、反映する。

cd django-app
git pull
cd app
docker-compose down
docker-compose build
docker-compose up -d

**Comment by quantumshiro** [comment]
#17 でソースコードの修正箇所については治っているのでmergeが通れば問題ないと考えています。

pythonのDockerfileに
``` yml
RUN python manage.py collectstatic
RUN python manage.py runserver 0.0.0.0:8000
```
を追記すれば問題なく動くと思っていたのですがどうですか

**Comment by sacky3105** [comment]
DEBUGの設定に関する問題は解決済みということでいったん閉じますね。

**Comment by sacky3105** [comment]
無事解決したので閉じます！！
