### ISSUE TITLE
Dockerfileへの追記

### ISSUE THREAD

**Issue by sacky3105** [sacky3105/django_app#16]
### 追加機能

Dockerでmanage.pyによりサーバーを動かす処理を作成する。

### どのように

Dockerfileにmanage.pyでサーバーを動かす処理を作成

**Comment by naritomo08** [comment]
以下のコマンドを入れましたが、ビルドコケました。

RUN python manage.py collectstatic
RUN python manage.py runserver 0.0.0.0:8000

**Comment by naritomo08** [comment]
以下の設定で解決するかも。

・Docker-compose.ymlにてwebメソッドの"Command"行を削除する。

・Dockerfileにて最後に以下を追記する。
COPY boot.sh /code/
RUN chmod +x /code/boot.sh
ENTRYPOINT ["./python/boot.sh"]

・python/Dockerfileと同じ場所にboot.shを作成し、以下の内容を記載する。

#!/bin/sh

cd /code
python manage.py collectstatic
python manage.py runserver 0.0.0.0:8000

コミットする。

サーバにて以下のコマンドを入力する。

cd django-app
git pull
cd app
docker-compose down
docker-compose build
docker-compose up -d

**Comment by sacky3105** [comment]
これは済んでいるということでいったん閉じますね。

**Comment by sacky3105** [comment]
解決したので閉じます！！
