### ISSUE TITLE
アプリ階層のREADME作成

### ISSUE THREAD

**Issue by sacky3105** [sacky3105/django_app#8]
### タスク

以下の情報を盛り込んでアプリ階層のREADMEを作成する。
①概要
②環境構築
③起動手順

### 担当者

主担当：タクーシュ

### タスク内容

1.1週間
2.0.2人/月

**Comment by naritomo08** [comment]
トップ階層のReadme.mdにまとめました。
もう取りまとめてしまったので、消してしまっていいかも。

**Comment by sacky3105** [comment]
分かりました。そしたら、これ閉じますね！！
